#-----------------------------------------------------------
# Copyright (C) 2025 Celia Buira
#-----------------------------------------------------------
# Licensed under the terms of GNU GPL 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#---------------------------------------------------------------------

from qgis.core import QgsExpression, qgsfunction, QgsGeometry, QgsPointXY

from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.PyQt.QtCore import QEasingCurve
from qgis.PyQt.QtGui import QVector2D

from statistics import mean

# from .easing import ease_in_circ as _ease_in_circ
from . import easing
from . import easing_autogenerated

def classFactory(iface):
    return MinimalPlugin(iface)


@qgsfunction(group="Animation", referenced_columns=[], handlesnull=True)
def lerp(start, end, t, unclamped=False):
    """
    <p> Equivalent of <i>scale_linear(t, 0, 1, start, end)</i> </p>
    <h4>Syntax</h4>
    <p><b>lerp</b>(  <i>start, end, value </i>)</p>

    <h4>Arguments</h4>
    <p><i>start</i> &rarr; placeholder</p>
    <p><i>end</i> &rarr; placeholder</p>
    <p><i>value</i> &rarr; placeholder</p>

    """
    if unclamped is None or unclamped != True:
        t = easing.clamp01(t)
        
    return (1-t) * start + t * end 


@qgsfunction(group="Animation", referenced_columns=[])
def lerp_unclamped(start, end, t, parent):
    """
    <p> Equivalent of <i>scale_linear(t, 0, 1, start, end)</i> </p>
    <h4>Syntax</h4>
    <p><b>lerp</b>(  <i>start, end, value </i>)</p>

    <h4>Arguments</h4>
    <p><i>start</i> &rarr; placeholder</p>
    <p><i>end</i> &rarr; placeholder</p>
    <p><i>value</i> &rarr; placeholder</p>
    """
    return (1-t) * start + t * end 


@qgsfunction(group="Animation", referenced_columns=[])
def inverse_lerp(start, end, value, parent):
    """
    <h4>Syntax</h4>
    <p><b>inverse_lerp</b>(  <i>start, stop, value </i>)</p>

    <h4>Arguments</h4>
    <p><i>start</i> &rarr; placeholder</p>
    <p><i>end</i> &rarr; placeholder</p>
    <p><i>value</i> &rarr; placeholder</p>
    """
    return easing.inverse_lerp(start, end, value)


@qgsfunction(group="Animation", referenced_columns=[])
def inverse_lerp_unclamped(start, end, value, parent):
    """
    <h4>Syntax</h4>
    <p><b>inverse_lerp</b>(  <i>start, stop, value </i>)</p>

    <h4>Arguments</h4>
    <p><i>start</i> &rarr; placeholder</p>
    <p><i>end</i> &rarr; placeholder</p>
    <p><i>value</i> &rarr; placeholder</p>
    """
    return easing.inverse_lerp_unclamped(start, end, value)


@qgsfunction(group="Animation", referenced_columns=[])
def remap(value, start1, stop1, start2, stop2):
    """
    <h4>Syntax</h4>
    <p><b>remap</b>( value, start1, stop1, start2, stop2 )</p>
    """
    t = easing.inverse_lerp(start1, stop1, value)
    #return t
    return start2 + (stop2 - start2) * t

@qgsfunction(group='Custom', referenced_columns=[])
def to_circle(geometry: QgsGeometry, t: float=1, goal:float=None):
    """
    Calculates the sum of the two parameters value1 and value2.
    <h2>Example usage:</h2>
    <ul>
      <li>my_sum(5, 8) -> 13</li>
      <li>my_sum("field1", "field2") -> 42</li>
    </ul>
    """
    centroid = geometry.pointOnSurface()
    
    vertices = [v for v in geometry.vertices()]
    vertices_as_geom = [QgsGeometry(v) for v in geometry.vertices()]
    
    distance_centroid_vertex = [v.distance(centroid) for v in vertices_as_geom]
    
    # TODO confirms optional argument works on older release
    if goal == None:
        goal = mean(distance_centroid_vertex)
    
    vectors = [QVector2D( v.toQPointF() - centroid.asQPointF()) for v in vertices]
    
    
    vectors = [vector.normalized() * easing.lerp_unclamped(original_dist, goal, t) for vector, original_dist in zip(vectors, distance_centroid_vertex)]
    end_vertices = [QgsPointXY(centroid.asQPointF() + final_vector.toPointF()) for final_vector in vectors]
    
    polygon = QgsGeometry.fromPolygonXY([end_vertices])
    return polygon

class MinimalPlugin:
    def __init__(self, iface):
        self.iface = iface

    def initGui(self):
        self.action = QAction('Go!', self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        self.iface.removeToolBarIcon(self.action)
        del self.action

        self.unloadExpressions()

    def run(self):
        QMessageBox.information(None, 'Minimal plugin', 'Do something useful here')

    def initExpressions(self):
        QgsExpression.registerFunction(inverse_lerp)

    def unloadExpressions(self):
        QgsExpression.unregisterFunction("lerp")
        QgsExpression.unregisterFunction("lerp_unclamped")
        QgsExpression.unregisterFunction("inverse_lerp")
        QgsExpression.unregisterFunction("inverse_lerp_unclamped")
        QgsExpression.unregisterFunction("remap")
        
        for easing_function in easing_autogenerated.registered_easing_functions:
            QgsExpression.unregisterFunction(easing_function)

