# /!\/!\warning/!\/!\
# autogenerated by generate_easing_function_expression.py

from qgis.PyQt.QtCore import QEasingCurve
from qgis.utils import qgsfunction

registered_easing_functions = {
    'ease_in_quad',
    'ease_out_quad',
    'ease_in_out_quad',
    'ease_out_in_quad',
    'ease_in_cubic',
    'ease_out_cubic',
    'ease_in_out_cubic',
    'ease_out_in_cubic',
    'ease_in_quart',
    'ease_out_quart',
    'ease_in_out_quart',
    'ease_out_in_quart',
    'ease_in_quint',
    'ease_out_quint',
    'ease_in_out_quint',
    'ease_out_in_quint',
    'ease_in_sine',
    'ease_out_sine',
    'ease_in_out_sine',
    'ease_out_in_sine',
    'ease_in_expo',
    'ease_out_expo',
    'ease_in_out_expo',
    'ease_out_in_expo',
    'ease_in_circ',
    'ease_out_circ',
    'ease_in_out_circ',
    'ease_out_in_circ',
    'ease_in_elastic',
    'ease_out_elastic',
    'ease_in_out_elastic',
    'ease_out_in_elastic',
    'ease_in_back',
    'ease_out_back',
    'ease_in_out_back',
    'ease_out_in_back',
    'ease_in_bounce',
    'ease_out_bounce',
    'ease_in_out_bounce',
    'ease_out_in_bounce',
}

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_quad(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InQuad </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_quad</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_quad</b>( 0.25 )  &rarr; 0.0625</li>
      <li><b>ease_in_quad</b>( 0.5 )  &rarr; 0.25</li>
      <li><b>ease_in_quad</b>( 0.75 )  &rarr; 0.5625</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InQuad)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_quad(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutQuad </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_quad</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_quad</b>( 0.25 )  &rarr; 0.4375</li>
      <li><b>ease_out_quad</b>( 0.5 )  &rarr; 0.75</li>
      <li><b>ease_out_quad</b>( 0.75 )  &rarr; 0.9375</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutQuad)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_quad(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutQuad </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_quad</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_quad</b>( 0.25 )  &rarr; 0.125</li>
      <li><b>ease_in_out_quad</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_in_out_quad</b>( 0.75 )  &rarr; 0.875</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutQuad)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_quad(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInQuad </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_quad</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_quad</b>( 0.25 )  &rarr; 0.375</li>
      <li><b>ease_out_in_quad</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_quad</b>( 0.75 )  &rarr; 0.625</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInQuad)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_cubic(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InCubic </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_cubic</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_cubic</b>( 0.25 )  &rarr; 0.01562…</li>
      <li><b>ease_in_cubic</b>( 0.5 )  &rarr; 0.125</li>
      <li><b>ease_in_cubic</b>( 0.75 )  &rarr; 0.42188…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InCubic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_cubic(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutCubic </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_cubic</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_cubic</b>( 0.25 )  &rarr; 0.57812…</li>
      <li><b>ease_out_cubic</b>( 0.5 )  &rarr; 0.875</li>
      <li><b>ease_out_cubic</b>( 0.75 )  &rarr; 0.98438…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutCubic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_cubic(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutCubic </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_cubic</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_cubic</b>( 0.25 )  &rarr; 0.0625</li>
      <li><b>ease_in_out_cubic</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_in_out_cubic</b>( 0.75 )  &rarr; 0.9375</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutCubic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_cubic(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInCubic </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_cubic</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_cubic</b>( 0.25 )  &rarr; 0.4375</li>
      <li><b>ease_out_in_cubic</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_cubic</b>( 0.75 )  &rarr; 0.5625</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInCubic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_quart(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InQuart </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_quart</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_quart</b>( 0.25 )  &rarr; 0.00391…</li>
      <li><b>ease_in_quart</b>( 0.5 )  &rarr; 0.0625</li>
      <li><b>ease_in_quart</b>( 0.75 )  &rarr; 0.31641…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InQuart)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_quart(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutQuart </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_quart</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_quart</b>( 0.25 )  &rarr; 0.68359…</li>
      <li><b>ease_out_quart</b>( 0.5 )  &rarr; 0.9375</li>
      <li><b>ease_out_quart</b>( 0.75 )  &rarr; 0.99609…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutQuart)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_quart(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutQuart </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_quart</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_quart</b>( 0.25 )  &rarr; 0.03125</li>
      <li><b>ease_in_out_quart</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_in_out_quart</b>( 0.75 )  &rarr; 0.96875</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutQuart)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_quart(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInQuart </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_quart</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_quart</b>( 0.25 )  &rarr; 0.46875</li>
      <li><b>ease_out_in_quart</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_quart</b>( 0.75 )  &rarr; 0.53125</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInQuart)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_quint(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InQuint </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_quint</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_quint</b>( 0.25 )  &rarr; 0.00098…</li>
      <li><b>ease_in_quint</b>( 0.5 )  &rarr; 0.03125</li>
      <li><b>ease_in_quint</b>( 0.75 )  &rarr; 0.2373…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InQuint)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_quint(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutQuint </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_quint</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_quint</b>( 0.25 )  &rarr; 0.7627…</li>
      <li><b>ease_out_quint</b>( 0.5 )  &rarr; 0.96875</li>
      <li><b>ease_out_quint</b>( 0.75 )  &rarr; 0.99902…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutQuint)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_quint(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutQuint </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_quint</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_quint</b>( 0.25 )  &rarr; 0.01562…</li>
      <li><b>ease_in_out_quint</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_in_out_quint</b>( 0.75 )  &rarr; 0.98438…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutQuint)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_quint(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInQuint </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_quint</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_quint</b>( 0.25 )  &rarr; 0.48438…</li>
      <li><b>ease_out_in_quint</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_quint</b>( 0.75 )  &rarr; 0.51562…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInQuint)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_sine(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InSine </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_sine</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_sine</b>( 0.25 )  &rarr; 0.07612…</li>
      <li><b>ease_in_sine</b>( 0.5 )  &rarr; 0.29289…</li>
      <li><b>ease_in_sine</b>( 0.75 )  &rarr; 0.61732…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InSine)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_sine(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutSine </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_sine</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_sine</b>( 0.25 )  &rarr; 0.38268…</li>
      <li><b>ease_out_sine</b>( 0.5 )  &rarr; 0.70711…</li>
      <li><b>ease_out_sine</b>( 0.75 )  &rarr; 0.92388…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutSine)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_sine(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutSine </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_sine</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_sine</b>( 0.25 )  &rarr; 0.14645…</li>
      <li><b>ease_in_out_sine</b>( 0.5 )  &rarr; 0.5…</li>
      <li><b>ease_in_out_sine</b>( 0.75 )  &rarr; 0.85355…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutSine)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_sine(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInSine </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_sine</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_sine</b>( 0.25 )  &rarr; 0.35355…</li>
      <li><b>ease_out_in_sine</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_sine</b>( 0.75 )  &rarr; 0.64645…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInSine)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_expo(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InExpo </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_expo</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_expo</b>( 0.25 )  &rarr; 0.00452…</li>
      <li><b>ease_in_expo</b>( 0.5 )  &rarr; 0.03025</li>
      <li><b>ease_in_expo</b>( 0.75 )  &rarr; 0.17578…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InExpo)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_expo(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutExpo </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_expo</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_expo</b>( 0.25 )  &rarr; 0.82405…</li>
      <li><b>ease_out_expo</b>( 0.5 )  &rarr; 0.96972…</li>
      <li><b>ease_out_expo</b>( 0.75 )  &rarr; 0.99547…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutExpo)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_expo(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutExpo </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_expo</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_expo</b>( 0.25 )  &rarr; 0.01512…</li>
      <li><b>ease_in_out_expo</b>( 0.5 )  &rarr; 0.50025</li>
      <li><b>ease_in_out_expo</b>( 0.75 )  &rarr; 0.98487…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutExpo)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_expo(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInExpo </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_expo</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_expo</b>( 0.25 )  &rarr; 0.48486…</li>
      <li><b>ease_out_in_expo</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_expo</b>( 0.75 )  &rarr; 0.51513…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInExpo)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_circ(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InCirc </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_circ</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_circ</b>( 0.25 )  &rarr; 0.03175…</li>
      <li><b>ease_in_circ</b>( 0.5 )  &rarr; 0.13397…</li>
      <li><b>ease_in_circ</b>( 0.75 )  &rarr; 0.33856…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InCirc)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_circ(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutCirc </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_circ</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_circ</b>( 0.25 )  &rarr; 0.66144…</li>
      <li><b>ease_out_circ</b>( 0.5 )  &rarr; 0.86603…</li>
      <li><b>ease_out_circ</b>( 0.75 )  &rarr; 0.96825…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutCirc)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_circ(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutCirc </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_circ</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_circ</b>( 0.25 )  &rarr; 0.06699…</li>
      <li><b>ease_in_out_circ</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_in_out_circ</b>( 0.75 )  &rarr; 0.93301…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutCirc)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_circ(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInCirc </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_circ</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_circ</b>( 0.25 )  &rarr; 0.43301…</li>
      <li><b>ease_out_in_circ</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_circ</b>( 0.75 )  &rarr; 0.56699…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInCirc)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_elastic(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InElastic </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_elastic</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_elastic</b>( 0.25 )  &rarr; -0.00552…</li>
      <li><b>ease_in_elastic</b>( 0.5 )  &rarr; -0.01563…</li>
      <li><b>ease_in_elastic</b>( 0.75 )  &rarr; 0.08839…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InElastic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_elastic(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutElastic </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_elastic</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_elastic</b>( 0.25 )  &rarr; 0.91161…</li>
      <li><b>ease_out_elastic</b>( 0.5 )  &rarr; 1.01562…</li>
      <li><b>ease_out_elastic</b>( 0.75 )  &rarr; 1.00552…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutElastic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_elastic(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutElastic </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_elastic</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_elastic</b>( 0.25 )  &rarr; -0.00781…</li>
      <li><b>ease_in_out_elastic</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_in_out_elastic</b>( 0.75 )  &rarr; 1.00781…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutElastic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_elastic(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInElastic </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_elastic</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_elastic</b>( 0.25 )  &rarr; 0.48438…</li>
      <li><b>ease_out_in_elastic</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_elastic</b>( 0.75 )  &rarr; 0.46875</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInElastic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_back(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InBack </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_back</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_back</b>( 0.25 )  &rarr; -0.06414…</li>
      <li><b>ease_in_back</b>( 0.5 )  &rarr; -0.0877…</li>
      <li><b>ease_in_back</b>( 0.75 )  &rarr; 0.18259…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InBack)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_back(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutBack </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_back</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_back</b>( 0.25 )  &rarr; 0.81741…</li>
      <li><b>ease_out_back</b>( 0.5 )  &rarr; 1.0877…</li>
      <li><b>ease_out_back</b>( 0.75 )  &rarr; 1.06414…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutBack)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_back(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutBack </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_back</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_back</b>( 0.25 )  &rarr; -0.09968…</li>
      <li><b>ease_in_out_back</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_in_out_back</b>( 0.75 )  &rarr; 1.09968…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutBack)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_back(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInBack </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_back</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_back</b>( 0.25 )  &rarr; 0.54385…</li>
      <li><b>ease_out_in_back</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_back</b>( 0.75 )  &rarr; 0.45615…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInBack)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_bounce(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InBounce </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_bounce</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_bounce</b>( 0.25 )  &rarr; 0.02734…</li>
      <li><b>ease_in_bounce</b>( 0.5 )  &rarr; 0.23438…</li>
      <li><b>ease_in_bounce</b>( 0.75 )  &rarr; 0.52734…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InBounce)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_bounce(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutBounce </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_bounce</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_bounce</b>( 0.25 )  &rarr; 0.47266…</li>
      <li><b>ease_out_bounce</b>( 0.5 )  &rarr; 0.76562…</li>
      <li><b>ease_out_bounce</b>( 0.75 )  &rarr; 0.97266…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutBounce)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_in_out_bounce(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::InOutBounce </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_in_out_bounce</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_in_out_bounce</b>( 0.25 )  &rarr; 0.11719…</li>
      <li><b>ease_in_out_bounce</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_in_out_bounce</b>( 0.75 )  &rarr; 0.88281…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.InOutBounce)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def ease_out_in_bounce(t, parent):
    """
    
    <p> See the documentation for the matching curve in Qt's QEasingCurve: <a href="https://doc.qt.io/qt-6/qeasingcurve.html#Type-enum"> QEasingCurve::OutInBounce </a>.  </p>
    <h4>Syntax</h4>
    <p><b>ease_out_in_bounce</b>(  <i> t </i>)</p>

    <h4>Arguments</h4>
    <p><i>t</i>: a float representing the progress of the animation (0 to 1)</p>


    
    <h4>Example usage</h4>
    <ul>
      <li><b>ease_out_in_bounce</b>( 0.25 )  &rarr; 0.26562…</li>
      <li><b>ease_out_in_bounce</b>( 0.5 )  &rarr; 0.5</li>
      <li><b>ease_out_in_bounce</b>( 0.75 )  &rarr; 0.73438…</li>
    </ul>
    """
    easing = QEasingCurve(QEasingCurve.Type.OutInBounce)
    return easing.valueForProgress(t)

