#-----------------------------------------------------------
# Copyright (C) 2025 Celia Buira
#-----------------------------------------------------------
# Licensed under the terms of GNU GPL 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#---------------------------------------------------------------------

from qgis.core import QgsExpression, qgsfunction, QgsGeometry, QgsPointXY

from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.PyQt.QtGui import QVector2D

from statistics import mean

# from .easing import ease_in_circ as _ease_in_circ
from . import easing
from . import easing_autogenerated

@qgsfunction(group="Animation", referenced_columns=[], handlesnull=True)
def lerp(start, end, t, unclamped=False):
    """
    <p> Linear interpolation (lerp) between <i>start</i> and <i>end</i> by <i>t</i>. </p>
    <p> can extrapolate beyond the start and end values if <i>unclamped</i> is set to true, and <i>t</i> is outside the range [0, 1]. </p>
    <p> Equivalent of <i>scale_linear(t, 0, 1, start, end)</i> </p>
    <h4>Syntax</h4>
    <p><b>lerp</b>(  <i>start, end, t[, unclamped=false]</i>)</p>

    <h4>Arguments</h4>
    <p><i>start</i>: The starting value of the interpolation.</p>
    <p><i>end</i>: The ending value of the interpolation.</p>
    <p><i>t</i>: The interpolation factor, typically between 0 and 1.</p>
    <p><i>unclamped</i>: If true, the interpolation will not be clamped between start and end values.</p>

    <h4>Example usage</h4>
    <ul>
      <li><b>lerp</b>( 0, 100, 0.25 )  &rarr; 25</li>
      <li><b>lerp</b>( 0, 100, 0.5 )  &rarr; 50</li>
      <li><b>lerp</b>( 0, 100, 1 )  &rarr; 100</li>
      <br>
      <li><b>lerp</b>( 0, 100, 1.2 )  &rarr; 100</li>
      <li><b>lerp</b>( 0, 100, 1.2, true )  &rarr; 120</li>
    </ul>
    """
    if unclamped is None or unclamped != True:
        t = easing.clamp01(t)
        
    return (1-t) * start + t * end 


@qgsfunction(group="Animation", referenced_columns=[])
def lerp_unclamped(start, end, t, parent):
    """
    <p> Linear interpolation (lerp) between <i>start</i> and <i>end</i> by <i>t</i>, but not bounded to the inferior and superior limits of the interpolation range. </p>
    <p> handy shortcut for lerp(start, end, t, unclamped=true) </p>
    <h4>Syntax</h4>
    <p><b>lerp_unclamped</b>(  <i>start, end, t </i>)</p>

    <h4>Arguments</h4>
    <p><i>start</i>: The starting value of the interpolation.</p>
    <p><i>end</i>: The ending value of the interpolation.</p>
    <p><i>t</i>: The interpolation factor, typically between 0 and 1.</p>
    
    <h4>Example usage</h4>
    <ul>
      <li><b>lerp_unclamped</b>( 2, 8, -0.1 )  &rarr; 1.4</li>
      <li><b>lerp_unclamped</b>( 0, 100, 1.2 )  &rarr; 120</li>
      <br>
      <li><b>lerp_unclamped</b>( 0, 100, 1 )  &rarr; 100</li>
    </ul>
    """
    return (1-t) * start + t * end 


@qgsfunction(group="Animation", referenced_columns=[])
def inverse_lerp(start, end, value, parent):
    """
    <p> Calculates the interpolation factor (t) that would produce the given <i>value</i> when linearly interpolating between <i>start</i> and <i>end</i>. </p>
    <h4>Syntax</h4>
    <p><b>inverse_lerp</b>(  <i>start, stop, value </i>)</p>

    <h4>Arguments</h4>
    <p><i>start</i>: The starting value of the interpolation.</p>
    <p><i>end</i>: The ending value of the interpolation.</p>
    <p><i>value</i>: The value for which to calculate the interpolation factor.</p>

    <h4>Example usage</h4>
    <ul>
      <li><b>inverse_lerp</b>( 0, 100, 25 )  &rarr; 0.25</li>
      <li><b>inverse_lerp</b>( 0, 100, 50 )  &rarr; 0.5</li>
      <li><b>inverse_lerp</b>( 0, 100, 100 )  &rarr; 1</li>
      <li><b>inverse_lerp</b>( 0, 100, 125 )  &rarr; 1</li>
    </ul>
    """
    return easing.inverse_lerp(start, end, value)


@qgsfunction(group="Animation", referenced_columns=[])
def inverse_lerp_unclamped(start, end, value, parent):
    """
    <p> Calculates the interpolation factor (t) that would produce the given <i>value</i> when linearly interpolating between <i>start</i> and <i>end</i>, without clamping the result to the [0, 1] range. </p>
    <h4>Syntax</h4>
    <p><b>inverse_lerp_unclamped</b>(  <i>start, stop, value </i>)</p>

    <h4>Arguments</h4>
    <p><i>start</i>: The starting value of the interpolation.</p>
    <p><i>end</i>: The ending value of the interpolation.</p>
    <p><i>value</i>: The value for which to calculate the interpolation factor.</p>
    <h4>Example usage</h4>
    <ul>
      <li><b>inverse_lerp_unclamped</b>( 0, 100, 125 )  &rarr; 1.25</li>
      <br>
      <li><b>inverse_lerp_unclamped</b>( 0, 100, 50 )  &rarr; 0.5</li>
      <li><b>inverse_lerp_unclamped</b>( 0, 100, 100 )  &rarr; 1</li>
    </ul>
    """
    return easing.inverse_lerp_unclamped(start, end, value)


@qgsfunction(group="Animation", referenced_columns=[])
def remap(value, start1, stop1, start2, stop2, unclamped=False):
    """
    <p>Remaps a value from one range to another.</p>
    <p>Equivalent to <i>scale_linear</i> but with a more intuitive name, and a new optional argument for unclamping the output.</p>
    <h4>Syntax</h4>
    <p><b>remap</b>( value, start1, stop1, start2, stop2[, unclamped=False )</p>
    <h4>Arguments</h4>
    <p><i>value</i>: The value to be remapped.</p>
    <p><i>start1</i>: The lower bound of the input range.</p>
    <p><i>stop1</i>: The upper bound of the input range.</p>
    <p><i>start2</i>: The lower bound of the output range.</p>
    <p><i>stop2</i>: The upper bound of the output range.</p>
    <p><i>unclamped</i>: If True, allows the output to exceed the output range.</p>
    <h4>Example usage</h4>
    <ul>
      <li><b>remap</b>( 2, 0, 10, 0, 100 )  &rarr; 20</li>
      <li><b>remap</b>( 12, 0, 10, 0, 100, true )  &rarr; 120</li>
    </ul>
    
    """
    if unclamped:
        t = easing.inverse_lerp_unclamped(start1, stop1, value)
    else:
        t = easing.inverse_lerp(start1, stop1, value)
    return start2 + (stop2 - start2) * t

@qgsfunction(group='Custom', referenced_columns=[])
def to_circle(geometry: QgsGeometry, t: float=1, goal:float=None):
    """
    Transforms the geometry into a circular shape by adjusting the vertices' distances from the centroid.

    Results depends on the number of vertices in the geometry, best results are obtained with a higher number of vertices.
    Results are not guaranteed on multi-part geometries.
    <h4>Syntax</h4>
    <p><b>to_circle</b>(  <i>geometry, t, goal </i>)</p>
    <h4>Arguments</h4>

    <p><i>geometry</i>: The input geometry to be transformed.</p>
    <p><i>t</i>: The interpolation factor, usually between 0 and 1, but can be outside for extrapolation.</p>
    <p><i>goal</i>: The target distance from the centroid for the vertices. If None, the mean distance vertices<=>centroid is used.</p>
    
    <h4>Example usage:</h4>
    <ul>
      <li>to_circle($geometry, 0.5) -> partially circular geometry</li>
      <li>to_circle($geometry) -> fully circular geometry</li>
    </ul>
    """
    centroid = geometry.pointOnSurface()
    
    vertices = [v for v in geometry.vertices()]
    vertices_as_geom = [QgsGeometry(v) for v in geometry.vertices()]
    
    distance_centroid_vertex = [v.distance(centroid) for v in vertices_as_geom]
    
    # TODO confirms optional argument works on older release
    if goal == None:
        goal = mean(distance_centroid_vertex)
    
    vectors = [QVector2D( v.toQPointF() - centroid.asQPointF()) for v in vertices]
    
    
    vectors = [vector.normalized() * easing.lerp_unclamped(original_dist, goal, t) for vector, original_dist in zip(vectors, distance_centroid_vertex)]
    end_vertices = [QgsPointXY(centroid.asQPointF() + final_vector.toPointF()) for final_vector in vectors]
    
    polygon = QgsGeometry.fromPolygonXY([end_vertices])
    return polygon

class YAAPPlugin:
    def __init__(self, iface):
        self.iface = iface

    def initGui(self):
        self.action = QAction('Go!', self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        self.iface.removeToolBarIcon(self.action)
        del self.action

        self.unloadExpressions()

    def run(self):
        QMessageBox.information(None, 'Minimal plugin', 'Do something useful here')

    def initExpressions(self):
        """Already registered via the decorator @qgsfunction, but I like to have a symmetry with unloadExpressions"""
        pass 

    def unloadExpressions(self):
        QgsExpression.unregisterFunction("lerp")
        QgsExpression.unregisterFunction("lerp_unclamped")
        QgsExpression.unregisterFunction("inverse_lerp")
        QgsExpression.unregisterFunction("inverse_lerp_unclamped")
        QgsExpression.unregisterFunction("remap")
        QgsExpression.unregisterFunction("to_circle")
        
        for easing_function in easing_autogenerated.registered_easing_functions:
            QgsExpression.unregisterFunction(easing_function)

