# /!\/!\warning/!\/!\
# autogenerated by generate_easing_function_expression.py

from qgis.PyQt.QtCore import QEasingCurve
from qgis.utils import qgsfunction

registred_easing_functions = {
    'in_quad'
    'out_quad'
    'in_out_quad'
    'out_in_quad'
    'in_cubic'
    'out_cubic'
    'in_out_cubic'
    'out_in_cubic'
    'in_quart'
    'out_quart'
    'in_out_quart'
    'out_in_quart'
    'in_quint'
    'out_quint'
    'in_out_quint'
    'out_in_quint'
    'in_sine'
    'out_sine'
    'in_out_sine'
    'out_in_sine'
    'in_expo'
    'out_expo'
    'in_out_expo'
    'out_in_expo'
    'in_circ'
    'out_circ'
    'in_out_circ'
    'out_in_circ'
    'in_elastic'
    'out_elastic'
    'in_out_elastic'
    'out_in_elastic'
    'in_back'
    'out_back'
    'in_out_back'
    'out_in_back'
    'in_bounce'
    'out_bounce'
    'in_out_bounce'
    'out_in_bounce'
}

@qgsfunction(group="Animation", referenced_columns=[])
def in_quad(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_quad</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InQuad)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_quad(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_quad</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutQuad)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_quad(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_quad</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutQuad)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_quad(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_quad</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInQuad)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_cubic(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_cubic</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InCubic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_cubic(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_cubic</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutCubic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_cubic(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_cubic</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutCubic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_cubic(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_cubic</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInCubic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_quart(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_quart</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InQuart)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_quart(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_quart</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutQuart)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_quart(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_quart</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutQuart)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_quart(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_quart</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInQuart)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_quint(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_quint</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InQuint)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_quint(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_quint</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutQuint)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_quint(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_quint</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutQuint)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_quint(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_quint</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInQuint)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_sine(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_sine</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InSine)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_sine(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_sine</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutSine)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_sine(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_sine</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutSine)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_sine(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_sine</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInSine)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_expo(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_expo</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InExpo)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_expo(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_expo</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutExpo)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_expo(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_expo</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutExpo)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_expo(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_expo</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInExpo)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_circ(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_circ</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InCirc)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_circ(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_circ</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutCirc)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_circ(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_circ</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutCirc)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_circ(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_circ</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInCirc)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_elastic(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_elastic</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InElastic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_elastic(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_elastic</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutElastic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_elastic(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_elastic</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutElastic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_elastic(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_elastic</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInElastic)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_back(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_back</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InBack)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_back(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_back</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutBack)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_back(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_back</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutBack)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_back(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_back</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInBack)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_bounce(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_bounce</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InBounce)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_bounce(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_bounce</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutBounce)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def in_out_bounce(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>in_out_bounce</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.InOutBounce)
    return easing.valueForProgress(t)

@qgsfunction(group="Animation", referenced_columns=[])
def out_in_bounce(t, parent):
    """
    <h4>Syntax</h4>
    <p><b>out_in_bounce</b>(  <i> t </i>)</p>
    """
    easing = QEasingCurve(QEasingCurve.OutInBounce)
    return easing.valueForProgress(t)

