import os
from qgis.PyQt.QtCore import QEasingCurve

def capitalized2snakecase(string):
    return "".join([("_"+i if i.isupper() else i) for i in string]).strip("_").lower()

"""
for i in QEasingCurve.Type:
    keep = False
    name = i.name
    if name.startswith("In"):
        keep = True
    if name.startswith("Out"):
        keep = True
    if name.startswith("InOut"):
        keep = True
    if name.startswith("OutIn"):
        keep = True
        
    if name == "InCurve" or name == "OutCurve":
        #legacy of Qt we don't care
        keep = False
    
    if keep:
        print(f'QEasingCurve.Type.{name}: "{name}",')        
"""

#itself Generate with code above 
mapping = {
    QEasingCurve.Type.InQuad: "InQuad",
    QEasingCurve.Type.OutQuad: "OutQuad",
    QEasingCurve.Type.InOutQuad: "InOutQuad",
    QEasingCurve.Type.OutInQuad: "OutInQuad",
    QEasingCurve.Type.InCubic: "InCubic",
    QEasingCurve.Type.OutCubic: "OutCubic",
    QEasingCurve.Type.InOutCubic: "InOutCubic",
    QEasingCurve.Type.OutInCubic: "OutInCubic",
    QEasingCurve.Type.InQuart: "InQuart",
    QEasingCurve.Type.OutQuart: "OutQuart",
    QEasingCurve.Type.InOutQuart: "InOutQuart",
    QEasingCurve.Type.OutInQuart: "OutInQuart",
    QEasingCurve.Type.InQuint: "InQuint",
    QEasingCurve.Type.OutQuint: "OutQuint",
    QEasingCurve.Type.InOutQuint: "InOutQuint",
    QEasingCurve.Type.OutInQuint: "OutInQuint",
    QEasingCurve.Type.InSine: "InSine",
    QEasingCurve.Type.OutSine: "OutSine",
    QEasingCurve.Type.InOutSine: "InOutSine",
    QEasingCurve.Type.OutInSine: "OutInSine",
    QEasingCurve.Type.InExpo: "InExpo",
    QEasingCurve.Type.OutExpo: "OutExpo",
    QEasingCurve.Type.InOutExpo: "InOutExpo",
    QEasingCurve.Type.OutInExpo: "OutInExpo",
    QEasingCurve.Type.InCirc: "InCirc",
    QEasingCurve.Type.OutCirc: "OutCirc",
    QEasingCurve.Type.InOutCirc: "InOutCirc",
    QEasingCurve.Type.OutInCirc: "OutInCirc",
    QEasingCurve.Type.InElastic: "InElastic",
    QEasingCurve.Type.OutElastic: "OutElastic",
    QEasingCurve.Type.InOutElastic: "InOutElastic",
    QEasingCurve.Type.OutInElastic: "OutInElastic",
    QEasingCurve.Type.InBack: "InBack",
    QEasingCurve.Type.OutBack: "OutBack",
    QEasingCurve.Type.InOutBack: "InOutBack",
    QEasingCurve.Type.OutInBack: "OutInBack",
    QEasingCurve.Type.InBounce: "InBounce",
    QEasingCurve.Type.OutBounce: "OutBounce",
    QEasingCurve.Type.InOutBounce: "InOutBounce",
    QEasingCurve.Type.OutInBounce: "OutInBounce",
}

# mapping = {k: capitalized2snakecase(v) for k, v in mapping.items()}


template = """@qgsfunction(group="Animation", referenced_columns=[])
def {name}(t, parent):
    \"""
    <h4>Syntax</h4>
    <p><b>{name}</b>(  <i> t </i>)</p>
    \"""
    easing = QEasingCurve(QEasingCurve.{qt_name})
    return easing.valueForProgress(t)"""

"""
for k, v in mapping.items():
    name = capitalized2snakecase(v)
    qt_name = k.name
    doc = template_doc.format(name=name)
    print(template.format(name=name, qt_name=qt_name, doc=doc))
    print("")
"""

target_file = r"C:\Users\Valentin\Documents\plugin-animation-interpolation-expressions\animation_interpolation_expressions\easing_autogenerated.py"

with open(target_file, "w+") as f:
    
    f.write( "# /!\\/!\\warning/!\\/!\\\n" )
    filename = os.path.basename(__file__)
    f.write( f"# autogenerated by {filename}\n\n" )
    f.write( "from qgis.PyQt.QtCore import QEasingCurve\n" )
    f.write("from qgis.utils import qgsfunction\n\n")
    
    f.write("registred_easing_functions = {\n")
    for k, v in mapping.items():
        
        f.write(f"    '{capitalized2snakecase(v)}'\n")
    f.write("}\n\n")
    
    
    for k, v in mapping.items():
        name = capitalized2snakecase(v)
        qt_name = k.name
        f.write(template.format(name=name, qt_name=qt_name) + "\n\n")
        